"""empty message

Revision ID: 04036fb7f213
Revises: 06fc896e23e4
Create Date: 2020-05-04 21:40:09.190973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04036fb7f213'
down_revision = '06fc896e23e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_to_application_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_to_application_site', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
