"""empty message

Revision ID: 04eb5c08faf6
Revises: f45b7d68ba58
Create Date: 2020-04-05 20:43:43.606150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04eb5c08faf6'
down_revision = 'f45b7d68ba58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'job_location',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'job_location',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
