"""empty message

Revision ID: 11ab152f609e
Revises: 58c0de4304d5
Create Date: 2020-05-04 21:39:03.024722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ab152f609e'
down_revision = '58c0de4304d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_to_application_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_to_application_site', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
