"""empty message

Revision ID: 1640fd3b134a
Revises: 7e8f8a1eb580
Create Date: 2020-04-05 20:48:27.172790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1640fd3b134a'
down_revision = '7e8f8a1eb580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_email', sa.String(length=120), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('apply_here_email', sa.String(length=120), nullable=True),
    sa.Column('job_location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_date_posted'), 'posts', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_date_posted'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
