"""empty message

Revision ID: 1b92db4fb0ce
Revises: 8541b8cbe108
Create Date: 2020-04-13 21:55:38.198618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b92db4fb0ce'
down_revision = '8541b8cbe108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_email', sa.String(length=120), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('apply_here_email', sa.String(length=120), nullable=True),
    sa.Column('link_to_application_site', sa.String(length=100), nullable=True),
    sa.Column('job_location', sa.String(length=120), nullable=True),
    sa.Column('org_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_date_posted'), 'posts', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_date_posted'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
