"""empty message

Revision ID: 35dc636a1717
Revises: 9539ea5f0a5a
Create Date: 2020-05-04 22:02:20.857842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dc636a1717'
down_revision = '9539ea5f0a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_to_application_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_to_application_site', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
