"""added org name

Revision ID: 492368de0f2c
Revises: 1640fd3b134a
Create Date: 2020-04-05 20:49:39.225702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492368de0f2c'
down_revision = '1640fd3b134a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('org_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'org_name')
    # ### end Alembic commands ###
