"""empty message

Revision ID: 58c0de4304d5
Revises: fb2d371d65f6
Create Date: 2020-05-04 21:37:27.869049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c0de4304d5'
down_revision = 'fb2d371d65f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_to_application_site', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_to_application_site')
    # ### end Alembic commands ###
