"""empty message

Revision ID: 7e8f8a1eb580
Revises: 3e9dfcd3bba7
Create Date: 2020-04-05 20:47:57.028771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8f8a1eb580'
down_revision = '3e9dfcd3bba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'poster_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.alter_column('posts', 'poster_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
