"""empty message

Revision ID: 9539ea5f0a5a
Revises: 04036fb7f213
Create Date: 2020-05-04 21:40:20.443236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9539ea5f0a5a'
down_revision = '04036fb7f213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_to_application_site', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_to_application_site')
    # ### end Alembic commands ###
