"""posts table

Revision ID: d8286c13bfd1
Revises: 
Create Date: 2020-04-05 20:36:22.209263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8286c13bfd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_email', sa.String(length=120), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('apply_here_email', sa.String(length=120), nullable=True),
    sa.Column('job_location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_date_posted'), 'posts', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_date_posted'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
