"""empty message

Revision ID: d8f50de077e4
Revises: 04eb5c08faf6
Create Date: 2020-04-05 20:44:34.024972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f50de077e4'
down_revision = '04eb5c08faf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'poster_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.alter_column('posts', 'poster_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
