"""added company name to posts

Revision ID: f45b7d68ba58
Revises: d8286c13bfd1
Create Date: 2020-04-05 20:39:20.089663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45b7d68ba58'
down_revision = 'd8286c13bfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('org_name', sa.String(length=120), nullable=False))
    op.alter_column('posts', 'job_location',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'job_location',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('posts', 'org_name')
    # ### end Alembic commands ###
