"""empty message

Revision ID: fb2d371d65f6
Revises: 9875ebb77c90
Create Date: 2020-05-04 21:37:07.831588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2d371d65f6'
down_revision = '9875ebb77c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_to_application_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_to_application_site', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
